language: c
matrix:
  include:
  # Python 3.5 with ghdl llvm
  - env: BUILD_NAME=ACCEPTANCE
    os: linux
    sudo: required
    dist: trusty
    before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gnat-4.8 zlib1g-dev
    - sudo apt-get install -y llvm-3.5-dev llvm-3.5-tools libedit-dev
    before_script:
    - cd ..
    - git clone --depth 1 https://github.com/tgingold/ghdl.git ghdl
    - cd ghdl
    - mkdir build-llvm
    - cd build-llvm
    - ../configure --with-llvm-config=llvm-config-3.5
    - make
    - sudo make install
    - cd ../..

install: true

script:
    - cd test; make all
